# Generated by Django 4.2.16 on 2024-11-08 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('curso', models.CharField(max_length=15)),
                ('edad', models.IntegerField()),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manejador_usuarios.colegio')),
            ],
        ),
    ]
