# Generated by Django 4.2.16 on 2024-11-08 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manejador_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('fecha', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='colegio',
        ),
        migrations.DeleteModel(
            name='Colegio',
        ),
        migrations.AddField(
            model_name='pago',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manejador_usuarios.estudiante'),
        ),
    ]
